INSTALLED_APPS = ["phplist"]

PHPLIST_BASE_URL = "http://localhost:9999/"
PHPLIST_LOGIN = "login"
PHPLIST_PASSWORD = "password"
PHPLIST_SECRET = "secret"
PHPLIST_LIST_ID = "4"

# Use plain StaticFilesStorage instead of CompressedManifestStaticFilesStorage
# during CI tests.  The manifest storage requires a pre-built staticfiles.json
# (generated by collectstatic), but CI runs setup --no-static which skips it.
# Without this override the ASGI child process crashes when servestatic resolves
# the staticfiles storage during middleware initialization.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
}
